//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDT_plugins.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HDT_plugins.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        internal static string Common_Back {
            get {
                return ResourceManager.GetString("Common_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (gold)  的本地化字符串。
        /// </summary>
        internal static string Common_GoldPrefix {
            get {
                return ResourceManager.GetString("Common_GoldPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No data 的本地化字符串。
        /// </summary>
        internal static string Common_NoData {
            get {
                return ResourceManager.GetString("Common_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string Common_None {
            get {
                return ResourceManager.GetString("Common_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This entry is available now, and the detailed feature is still in progress. 的本地化字符串。
        /// </summary>
        internal static string Common_PlaceholderDeveloping {
            get {
                return ResourceManager.GetString("Common_PlaceholderDeveloping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 +{0} 的本地化字符串。
        /// </summary>
        internal static string Common_RatingDeltaPositive {
            get {
                return ResourceManager.GetString("Common_RatingDeltaPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coming soon 的本地化字符串。
        /// </summary>
        internal static string Common_Todo {
            get {
                return ResourceManager.GetString("Common_Todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:yyyy-MM-dd} ~ {1:yyyy-MM-dd} 的本地化字符串。
        /// </summary>
        internal static string Common_WeekRangeFormat {
            get {
                return ResourceManager.GetString("Common_WeekRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string GameRace_ALL {
            get {
                return ResourceManager.GetString("GameRace_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beast 的本地化字符串。
        /// </summary>
        internal static string GameRace_BEAST {
            get {
                return ResourceManager.GetString("GameRace_BEAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string GameRace_BLANK {
            get {
                return ResourceManager.GetString("GameRace_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Demon 的本地化字符串。
        /// </summary>
        internal static string GameRace_DEMON {
            get {
                return ResourceManager.GetString("GameRace_DEMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dragon 的本地化字符串。
        /// </summary>
        internal static string GameRace_DRAGON {
            get {
                return ResourceManager.GetString("GameRace_DRAGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Elemental 的本地化字符串。
        /// </summary>
        internal static string GameRace_ELEMENTAL {
            get {
                return ResourceManager.GetString("GameRace_ELEMENTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mech 的本地化字符串。
        /// </summary>
        internal static string GameRace_MECHANICAL {
            get {
                return ResourceManager.GetString("GameRace_MECHANICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Murloc 的本地化字符串。
        /// </summary>
        internal static string GameRace_MURLOC {
            get {
                return ResourceManager.GetString("GameRace_MURLOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Naga 的本地化字符串。
        /// </summary>
        internal static string GameRace_NAGA {
            get {
                return ResourceManager.GetString("GameRace_NAGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pirate 的本地化字符串。
        /// </summary>
        internal static string GameRace_PIRATE {
            get {
                return ResourceManager.GetString("GameRace_PIRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quilboar 的本地化字符串。
        /// </summary>
        internal static string GameRace_QUILBOAR {
            get {
                return ResourceManager.GetString("GameRace_QUILBOAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Totem 的本地化字符串。
        /// </summary>
        internal static string GameRace_TOTEM {
            get {
                return ResourceManager.GetString("GameRace_TOTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undead 的本地化字符串。
        /// </summary>
        internal static string GameRace_UNDEAD {
            get {
                return ResourceManager.GetString("GameRace_UNDEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anomaly: {0} 的本地化字符串。
        /// </summary>
        internal static string HistoryMatches_AnomalyFormat {
            get {
                return ResourceManager.GetString("HistoryMatches_AnomalyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Day 的本地化字符串。
        /// </summary>
        internal static string HistoryMatches_DayRange {
            get {
                return ResourceManager.GetString("HistoryMatches_DayRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matches found for the current filter 的本地化字符串。
        /// </summary>
        internal static string HistoryMatches_Empty {
            get {
                return ResourceManager.GetString("HistoryMatches_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Final Board: {0} 的本地化字符串。
        /// </summary>
        internal static string HistoryMatches_FinalBoardFormat {
            get {
                return ResourceManager.GetString("HistoryMatches_FinalBoardFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Season 的本地化字符串。
        /// </summary>
        internal static string HistoryMatches_SeasonRange {
            get {
                return ResourceManager.GetString("HistoryMatches_SeasonRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matches: 0    Avg Placement: -    Rating Delta: - 的本地化字符串。
        /// </summary>
        internal static string HistoryMatches_SummaryEmpty {
            get {
                return ResourceManager.GetString("HistoryMatches_SummaryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matches: {0}  Avg Placement: {1:F2}  Rating Delta: {2} 的本地化字符串。
        /// </summary>
        internal static string HistoryMatches_SummaryFormat {
            get {
                return ResourceManager.GetString("HistoryMatches_SummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time: {0}    Placement: {1}    Rating: {2}    Delta: {3} 的本地化字符串。
        /// </summary>
        internal static string HistoryMatches_TimeRatingFormat {
            get {
                return ResourceManager.GetString("HistoryMatches_TimeRatingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match History 的本地化字符串。
        /// </summary>
        internal static string HistoryMatches_Title {
            get {
                return ResourceManager.GetString("HistoryMatches_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Week 的本地化字符串。
        /// </summary>
        internal static string HistoryMatches_WeekRange {
            get {
                return ResourceManager.GetString("HistoryMatches_WeekRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Final Board: 的本地化字符串。
        /// </summary>
        internal static string MatchDetail_FinalBoard {
            get {
                return ResourceManager.GetString("MatchDetail_FinalBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Final Hero Power: {0} 的本地化字符串。
        /// </summary>
        internal static string MatchDetail_FinalHeroPowerFormat {
            get {
                return ResourceManager.GetString("MatchDetail_FinalHeroPowerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Placement: {0}   Rating: {1}   Rating Delta: {2} 的本地化字符串。
        /// </summary>
        internal static string MatchDetail_HeaderStatsFormat {
            get {
                return ResourceManager.GetString("MatchDetail_HeaderStatsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected Hero: {0} 的本地化字符串。
        /// </summary>
        internal static string MatchDetail_SelectedHeroFormat {
            get {
                return ResourceManager.GetString("MatchDetail_SelectedHeroFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No tavern upgrade data 的本地化字符串。
        /// </summary>
        internal static string MatchDetail_TavernChartEmpty {
            get {
                return ResourceManager.GetString("MatchDetail_TavernChartEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tavern Progress 的本地化字符串。
        /// </summary>
        internal static string MatchDetail_TavernSection {
            get {
                return ResourceManager.GetString("MatchDetail_TavernSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn: {0}{1}Tier: {2} 的本地化字符串。
        /// </summary>
        internal static string MatchDetail_TavernTooltipFormat {
            get {
                return ResourceManager.GetString("MatchDetail_TavernTooltipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn-Tier: No data 的本地化字符串。
        /// </summary>
        internal static string MatchDetail_TavernUpgradeEmpty {
            get {
                return ResourceManager.GetString("MatchDetail_TavernUpgradeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn-Tier: {0} 的本地化字符串。
        /// </summary>
        internal static string MatchDetail_TavernUpgradeFormat {
            get {
                return ResourceManager.GetString("MatchDetail_TavernUpgradeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time: {0} 的本地化字符串。
        /// </summary>
        internal static string MatchDetail_TimeFormat {
            get {
                return ResourceManager.GetString("MatchDetail_TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match Detail 的本地化字符串。
        /// </summary>
        internal static string MatchDetail_Title {
            get {
                return ResourceManager.GetString("MatchDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attack 的本地化字符串。
        /// </summary>
        internal static string Minion_Attack {
            get {
                return ResourceManager.GetString("Minion_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Health 的本地化字符串。
        /// </summary>
        internal static string Minion_Health {
            get {
                return ResourceManager.GetString("Minion_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attack: {0} 的本地化字符串。
        /// </summary>
        internal static string MinionTooltip_AttackFormat {
            get {
                return ResourceManager.GetString("MinionTooltip_AttackFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Golden: {0} 的本地化字符串。
        /// </summary>
        internal static string MinionTooltip_GoldenFormat {
            get {
                return ResourceManager.GetString("MinionTooltip_GoldenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string MinionTooltip_GoldenNo {
            get {
                return ResourceManager.GetString("MinionTooltip_GoldenNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string MinionTooltip_GoldenYes {
            get {
                return ResourceManager.GetString("MinionTooltip_GoldenYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Health: {0} 的本地化字符串。
        /// </summary>
        internal static string MinionTooltip_HealthFormat {
            get {
                return ResourceManager.GetString("MinionTooltip_HealthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID: {0} 的本地化字符串。
        /// </summary>
        internal static string MinionTooltip_IdFormat {
            get {
                return ResourceManager.GetString("MinionTooltip_IdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keywords: {0} 的本地化字符串。
        /// </summary>
        internal static string MinionTooltip_KeywordsFormat {
            get {
                return ResourceManager.GetString("MinionTooltip_KeywordsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name: {0} 的本地化字符串。
        /// </summary>
        internal static string MinionTooltip_NameFormat {
            get {
                return ResourceManager.GetString("MinionTooltip_NameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position: {0} 的本地化字符串。
        /// </summary>
        internal static string MinionTooltip_PositionFormat {
            get {
                return ResourceManager.GetString("MinionTooltip_PositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Race: {0} 的本地化字符串。
        /// </summary>
        internal static string MinionTooltip_RaceFormat {
            get {
                return ResourceManager.GetString("MinionTooltip_RaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Plugin_ButtonText {
            get {
                return ResourceManager.GetString("Plugin_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Track Battlegrounds hero picks and placements 的本地化字符串。
        /// </summary>
        internal static string Plugin_Description {
            get {
                return ResourceManager.GetString("Plugin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battlegrounds Analytics 的本地化字符串。
        /// </summary>
        internal static string Plugin_MenuHeader {
            get {
                return ResourceManager.GetString("Plugin_MenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battlegrounds Analytics 的本地化字符串。
        /// </summary>
        internal static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If disabled, the plugin still loads but the window will not pop up automatically at HDT startup. 的本地化字符串。
        /// </summary>
        internal static string Settings_AutoOpenHint {
            get {
                return ResourceManager.GetString("Settings_AutoOpenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the Battlegrounds Analytics window automatically when HDT starts 的本地化字符串。
        /// </summary>
        internal static string Settings_AutoOpenOnStartup {
            get {
                return ResourceManager.GetString("Settings_AutoOpenOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin Settings 的本地化字符串。
        /// </summary>
        internal static string Settings_Header {
            get {
                return ResourceManager.GetString("Settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English (US) 的本地化字符串。
        /// </summary>
        internal static string Settings_LanguageEnUs {
            get {
                return ResourceManager.GetString("Settings_LanguageEnUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Settings_LanguageLabel {
            get {
                return ResourceManager.GetString("Settings_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simplified Chinese 的本地化字符串。
        /// </summary>
        internal static string Settings_LanguageZhCn {
            get {
                return ResourceManager.GetString("Settings_LanguageZhCn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Battlegrounds Analytics - Settings 的本地化字符串。
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hero Stats 的本地化字符串。
        /// </summary>
        internal static string Sidebar_Heroes {
            get {
                return ResourceManager.GetString("Sidebar_Heroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match History 的本地化字符串。
        /// </summary>
        internal static string Sidebar_History {
            get {
                return ResourceManager.GetString("Sidebar_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match Stats 的本地化字符串。
        /// </summary>
        internal static string Sidebar_Matches {
            get {
                return ResourceManager.GetString("Sidebar_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Race Stats 的本地化字符串。
        /// </summary>
        internal static string Sidebar_Races {
            get {
                return ResourceManager.GetString("Sidebar_Races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Sidebar_Settings {
            get {
                return ResourceManager.GetString("Sidebar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No TAG 的本地化字符串。
        /// </summary>
        internal static string Tags_Empty {
            get {
                return ResourceManager.GetString("Tags_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up to 5 tags are supported 的本地化字符串。
        /// </summary>
        internal static string Tags_MaxReached {
            get {
                return ResourceManager.GetString("Tags_MaxReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No available tags to add 的本地化字符串。
        /// </summary>
        internal static string Tags_NoAvailable {
            get {
                return ResourceManager.GetString("Tags_NoAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 season12 patch35.0 的本地化字符串。
        /// </summary>
        internal static string VersionInfo_DefaultDisplay {
            get {
                return ResourceManager.GetString("VersionInfo_DefaultDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No additional version data 的本地化字符串。
        /// </summary>
        internal static string VersionInfo_NoMoreData {
            get {
                return ResourceManager.GetString("VersionInfo_NoMoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string VersionInfo_Title {
            get {
                return ResourceManager.GetString("VersionInfo_Title", resourceCulture);
            }
        }
    }
}
